"""Run the Phase 4 candidate-map workflow and Phase 5 from hosted composite COGs.

This script writes map-derived candidates, baseline maps, postprocessed maps,
change rasters, 1 km association outputs, JSON metadata, and a run manifest.
It does not create or infer reference labels. Run it in Colab/Kaggle Python 3.11.
"""
from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import geopandas as gpd
import numpy as np
import rasterio
import xarray as xr
from libpysal.weights import Queen

from geointel.change.detection import compute_spatial_change_masks, compute_transition_matrix
from geointel.change.accuracy import evaluate_labels_csv
from geointel.change.association import area_adjusted_estimate_from_labels
from geointel.change.indices import compute_ndvi
from geointel.change.ndvi_baseline import ndvi_difference_baseline
from geointel.change.postprocess import postprocess_class_map
from geointel.gis.core import make_fishnet
from geointel.utils.config import load_config
from scripts.phase4_candidates import BANDS, make_rule_map
from scripts.sample_labels import create_candidate_files


def read_composite(path: Path) -> tuple[np.ndarray, dict[str, object]]:
    with rasterio.open(path) as source:
        if source.count != 6 or source.crs is None:
            raise ValueError(f"Expected six-band georeferenced composite: {path}")
        return source.read().astype("float32"), source.profile.copy()


def write_raster(path: Path, values: np.ndarray, profile: dict[str, object], description: str, nodata: int | float) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    out_profile = profile.copy()
    out_profile.update(count=1, dtype=values.dtype, nodata=nodata, compress="deflate")
    with rasterio.open(path, "w", **out_profile) as dst:
        dst.write(values, 1)
        dst.set_band_description(1, description)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", type=Path, default=Path("config/config.yaml"))
    parser.add_argument("--t1-composite", type=Path, required=True)
    parser.add_argument("--t2-composite", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--run-metadata", type=Path, help="metadata.json from scripts/colab_run.py")
    parser.add_argument("--labels", type=Path, help="completed manual labels CSV; never generated by this script")
    parser.add_argument("--labeller", help="single labeller used for independent accuracy evaluation")
    parser.add_argument("--area-labeler", help="single labeller for the optional area adjustment")
    parser.add_argument("--probability-sample", action="store_true", help="assert supplied labels are a probability sample")
    parser.add_argument("--permutations", type=int, default=999)
    args = parser.parse_args()
    if sys.version_info[:2] != (3, 11):
        raise RuntimeError(f"Hosted Phase 4/5 runner requires Python 3.11; found {sys.version.split()[0]}")
    cfg = load_config(args.config)
    output = args.output_dir.resolve()
    output.mkdir(parents=True, exist_ok=True)
    t1, profile = read_composite(args.t1_composite)
    t2, profile2 = read_composite(args.t2_composite)
    if t1.shape != t2.shape or profile["transform"] != profile2["transform"] or profile["crs"] != profile2["crs"]:
        raise ValueError("T1/T2 composites must share exactly the same grid")
    print(f"Python: {sys.version.split()[0]}")
    print(f"GDAL: {rasterio.__gdal_version__}; rasterio: {rasterio.__version__}")
    run_metadata_path = args.run_metadata
    if run_metadata_path is None:
        possible = args.t1_composite.parent.parent / "metadata.json"
        run_metadata_path = possible if possible.exists() else None
    upstream = json.loads(run_metadata_path.read_text(encoding="utf-8")) if run_metadata_path else {}
    print(f"Provider: {upstream.get('provider', 'unknown; no metadata.json supplied')}")
    print(f"T1 source: {args.t1_composite}; T2 source: {args.t2_composite}")
    scene_groups = upstream.get("epochs", {})
    for epoch in ("t1", "t2"):
        ids = [row.get("id", "unknown") for row in scene_groups.get(epoch, [])]
        print(f"{epoch.upper()} scene IDs: {json.dumps(ids) if ids else 'unknown; no upstream metadata supplied'}")
    print(f"Config hash: {cfg['_config_hash']}; AOI: {cfg['aoi']['name']}")

    candidate_dir = output / "phase4_candidates"
    raw1_path = make_rule_map(args.t1_composite, candidate_dir / "lulc_t1_rule.tif")
    raw2_path = make_rule_map(args.t2_composite, candidate_dir / "lulc_t2_rule.tif")
    create_candidate_files(
        raw1_path, raw2_path, candidate_dir / "labels",
        samples_per_class=int(cfg["classifier"]["target_labels_per_class"]),
        seed=int(cfg["reproducibility"]["numpy_seed"]),
    )
    with rasterio.open(raw1_path) as source:
        raw1 = source.read(1)
    with rasterio.open(raw2_path) as source:
        raw2 = source.read(1)
    cfg_change = cfg["change"]
    t1_final, pp1 = postprocess_class_map(
        raw1, int(cfg_change["majority_filter_size"]), float(cfg_change["minimum_mapping_unit_ha"]),
        float(cfg["resolution"]["reference_m"]), connectivity=int(cfg_change.get("connectivity", 8)),
    )
    t2_final, pp2 = postprocess_class_map(
        raw2, int(cfg_change["majority_filter_size"]), float(cfg_change["minimum_mapping_unit_ha"]),
        float(cfg["resolution"]["reference_m"]), connectivity=int(cfg_change.get("connectivity", 8)),
    )
    map1 = output / "lulc_t1_postprocessed.tif"
    map2 = output / "lulc_t2_postprocessed.tif"
    write_raster(map1, t1_final.astype("uint8"), profile, "T1 postprocessed 5-class baseline", 0)
    write_raster(map2, t2_final.astype("uint8"), profile, "T2 postprocessed 5-class baseline", 0)

    composite1 = xr.DataArray(t1, dims=("band", "y", "x"), coords={"band": BANDS})
    composite2 = xr.DataArray(t2, dims=("band", "y", "x"), coords={"band": BANDS})
    ndvi_result = ndvi_difference_baseline(
        compute_ndvi(composite1.sel(band="B08"), composite1.sel(band="B04")),
        compute_ndvi(composite2.sel(band="B08"), composite2.sel(band="B04")),
        float(cfg_change["ndvi_diff_threshold"]),
    )
    pixel_m = float(cfg["resolution"]["reference_m"])
    ndvi_profile = profile.copy()
    ndvi_profile.update(dtype="float32")
    write_raster(output / "ndvi_difference_t2_minus_t1.tif", ndvi_result["difference_t2_minus_t1"], ndvi_profile, "NDVI T2 minus T1", np.nan)
    write_raster(output / "ndvi_decline_baseline.tif", ndvi_result["decline_mask"], profile, "NDVI decline baseline", 255)

    transition = compute_transition_matrix(t1_final, t2_final, pixel_size_m=pixel_m)
    masks = compute_spatial_change_masks(t1_final, t2_final)
    urban_path, vegetation_path = output / "urban_expansion.tif", output / "vegetation_loss.tif"
    jointly_valid = np.isin(t1_final, [1, 2, 3, 4, 5]) & np.isin(t2_final, [1, 2, 3, 4, 5])
    urban_mask = masks["urban_expansion"].copy()
    vegetation_mask = masks["vegetation_loss"].copy()
    urban_mask[~jointly_valid] = 255
    vegetation_mask[~jointly_valid] = 255
    write_raster(urban_path, urban_mask, profile, "T1 nonbuilt to T2 built-up", 255)
    write_raster(vegetation_path, vegetation_mask, profile, "T1 vegetation to T2 nonvegetation", 255)

    aoi_path = Path(cfg["_repo_root"]) / cfg["aoi"]["path"]
    aoi = gpd.read_file(aoi_path)
    grid = make_fishnet(aoi, float(cfg_change["grid_cell_size_m"]))
    if grid.empty:
        raise ValueError("Approved AOI produced an empty association grid")
    # Aggregate raster change indicators in the same metric grid.
    from geointel.change.association import aggregate_binary_masks_to_grid, summarize_association

    grid = aggregate_binary_masks_to_grid(str(urban_path), str(vegetation_path), grid, pixel_m**2)
    weights = Queen.from_dataframe(grid, use_index=False)
    assoc = summarize_association(
        grid["urban_gain_ha"].to_numpy(), grid["vegetation_loss_ha"].to_numpy(), weights,
        alpha=float(cfg["association"]["alpha"]), top_n=int(cfg["association"]["top_n_hotspots"]),
        permutations=args.permutations, seed=int(cfg["reproducibility"]["numpy_seed"]),
    )
    z = assoc["gi_star"]["z_scores"]
    p = assoc["gi_star"]["permutation_p_values"]
    grid["gi_star_z"] = z
    grid["gi_star_p"] = p
    grid["hotspot_rank"] = [next((rank for rank, row in enumerate(assoc["top_n_hotspots"], 1) if row["grid_position"] == i), None) for i in range(len(grid))]
    grid_path = output / "association_grid.gpkg"
    grid.to_file(grid_path, driver="GPKG")
    assoc["output_grid"] = grid_path.name
    # The manual label template is intentionally empty; no area adjustment or accuracy run.
    accuracy_results: dict[str, object] = {}
    area_results: dict[str, object] | str = "NOT RUN; requires completed probability-sampled manual labels"
    if args.labels:
        for epoch, prediction in (("t1", map1), ("t2", map2)):
            try:
                accuracy_results[epoch] = evaluate_labels_csv(
                    args.labels, prediction, epoch=epoch,
                    random_state=int(cfg["reproducibility"]["numpy_seed"]),
                    labeller=args.labeller,
                )
            except (ValueError, KeyError) as exc:
                accuracy_results[epoch] = {"status": "NOT AVAILABLE", "reason": str(exc)}
        if args.probability_sample and args.area_labeler:
            area_results = {
                epoch: area_adjusted_estimate_from_labels(
                    str(prediction), str(args.labels), epoch, args.area_labeler, pixel_m**2
                )
                for epoch, prediction in (("t1", map1), ("t2", map2))
            }
        elif args.probability_sample or args.area_labeler:
            area_results = "NOT RUN; supply both --probability-sample and --area-labeler"

    metadata = {
        "generated_utc": datetime.now(timezone.utc).isoformat(),
        "config_hash": cfg["_config_hash"],
        "aoi": cfg["aoi"]["name"],
        "composites": {"t1": str(args.t1_composite), "t2": str(args.t2_composite)},
        "upstream_run_metadata": str(run_metadata_path) if run_metadata_path else None,
        "phase4": {
            "classification": "rule-based candidates only; not validated reference labels",
            "candidate_files": str(candidate_dir / "labels"),
            "reference_labels_created": 0,
            "accuracy": accuracy_results if args.labels else "NOT RUN; requires completed manual reference labels",
        },
        "postprocessing": {"t1": pp1, "t2": pp2},
        "ndvi_baseline": {
            "threshold": ndvi_result["threshold"],
            "valid_pixels": ndvi_result["valid_pixels"],
            "decline_pixels": ndvi_result["decline_pixels"],
            "interpretation": "descriptive NDVI decline baseline; not causal attribution",
        },
        "transition_joint_valid": transition,
        "association": assoc,
        "area_adjusted_estimate": area_results,
        "external_validation": "NOT RUN; supply downloaded external rasters to scripts/validate_external.py",
    }
    metadata_path = output / "phase45_metadata.json"
    metadata_path.write_text(json.dumps(metadata, indent=2), encoding="utf-8")
    manifest = {
        "status": "COMPLETED WHEN THIS SCRIPT RUNS SUCCESSFULLY; current repository has not run it on real composites",
        "generated_utc": metadata["generated_utc"],
        "config_hash": cfg["_config_hash"],
        "inputs": {"t1_composite": str(args.t1_composite), "t2_composite": str(args.t2_composite)},
        "outputs": [
            map1.name, map2.name, "ndvi_difference_t2_minus_t1.tif", "ndvi_decline_baseline.tif",
            urban_path.name, vegetation_path.name, grid_path.name, metadata_path.name,
        ],
        "manual_labels_created": 0,
    }
    (output / "run_manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    print(f"Wrote Phase 4/5 products under {output}")
    print("Reference labels created: 0; accuracy and area-adjusted estimate: NOT RUN")


if __name__ == "__main__":
    main()
